// <auto-generated />
using System;
using Aplikacija.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Aplikacija.Migrations
{
    [DbContext(typeof(AplikacijaContext))]
    [Migration("20210417095223_AppModel")]
    partial class AppModel
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.5")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Aplikacija.Models.Predbiljezba", b =>
                {
                    b.Property<int>("IdPredbiljezba")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Adresa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Datum")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdSeminar")
                        .HasColumnType("int");

                    b.Property<string>("Ime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prezime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SeminarIdSeminar")
                        .HasColumnType("int");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<string>("Telefon")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdPredbiljezba");

                    b.HasIndex("SeminarIdSeminar");

                    b.ToTable("Predbiljezba");
                });

            modelBuilder.Entity("Aplikacija.Models.Seminar", b =>
                {
                    b.Property<int>("IdSeminar")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Datum")
                        .HasColumnType("datetime2");

                    b.Property<string>("Naziv")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Opis")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Popunjen")
                        .HasColumnType("bit");

                    b.HasKey("IdSeminar");

                    b.ToTable("Seminar");
                });

            modelBuilder.Entity("Aplikacija.Models.Zaposlenik", b =>
                {
                    b.Property<int>("IdZaposlenik")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Ime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KorisnickoIme")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prezime")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdZaposlenik");

                    b.ToTable("Zaposlenik");
                });

            modelBuilder.Entity("Aplikacija.Models.Predbiljezba", b =>
                {
                    b.HasOne("Aplikacija.Models.Seminar", "Seminar")
                        .WithMany("Predbiljezbas")
                        .HasForeignKey("SeminarIdSeminar");

                    b.Navigation("Seminar");
                });

            modelBuilder.Entity("Aplikacija.Models.Seminar", b =>
                {
                    b.Navigation("Predbiljezbas");
                });
#pragma warning restore 612, 618
        }
    }
}
